# Generated by Django 3.1.4 on 2021-05-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiggy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default='', editable=False, max_length=30),
        ),
    ]
