# Generated by Django 3.1.4 on 2021-05-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiggy', '0002_auto_20210505_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
