# Generated by Django 3.1.4 on 2021-05-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiggy', '0003_auto_20210505_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='Users',
        ),
    ]
