# Generated by Django 3.1.4 on 2021-05-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiggy', '0004_auto_20210505_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
